import { spec, type Archetype } from './model';

/**
 * The layout archetypes. Order follows the research doc
 * (`engineering/architecture/analysis/layout-atlas/layout-atlas.md` § Layout archetypes).
 */
export const Archetypes: ReadonlyArray<Archetype> = [
  {
    id: 'top-bar-workspace',
    name: 'Top-bar workspace',
    summary: 'A sticky top bar carries a few destinations; the content below takes the full width.',
    spec: spec({ nav: 'top', local: 'filters', content: 'kanban' }),
    anatomy: [
      'Top bar: brand, 3–7 destinations, actions',
      'Local strip: view switch and filters',
      'Full-width content',
    ],
    shines: [
      'Content-first apps with a handful of stable top-level destinations',
      'Wide boards, tables and galleries that need every horizontal pixel',
      'Apps where people stay in one area for a long session',
    ],
    avoid: [
      'More than about seven destinations, or a list that keeps growing',
      'Deep hierarchies — never three levels in one bar',
      'Constant switching between many areas',
    ],
    examples: [
      { app: 'Haven', note: 'CRM: app switcher in a translucent top bar; board, grid and table below' },
      { app: 'Wheelhouse', note: 'Five destinations in a glass top bar over the studio workspace' },
    ],
    related: ['sidebar-shell', 'collection-drawer', 'board'],
    tags: ['top-nav', 'content-first'],
  },
  {
    id: 'sidebar-shell',
    name: 'Sidebar shell',
    summary: 'Grouped vertical navigation on the left, a header, and the page.',
    spec: spec({ nav: 'side', content: 'table', local: 'tabs' }),
    anatomy: ['Sidebar: grouped destinations with icons and counts', 'Header: page title and actions', 'Page content'],
    shines: [
      'Many or growing destinations; grouped sections; long labels',
      'Admin consoles and back offices people navigate all day',
      'Wide screens, where vertical lists scan faster than horizontal ones',
    ],
    avoid: [
      'Canvas tools, where the sidebar steals the hero’s width',
      'Small apps with three destinations — the column is mostly empty',
    ],
    examples: [{ app: 'SDK', note: 'SidebarMenu with sections, groups and an icon rail mode' }],
    related: ['icon-rail', 'top-bar-workspace', 'settings'],
    tags: ['side-nav', 'admin'],
  },
  {
    id: 'icon-rail',
    name: 'Icon rail + list',
    summary: 'A slim icon rail switches modes; each mode owns a list panel beside the work.',
    spec: spec({ nav: 'rail', leading: 'library', content: 'detail', density: 'compact' }),
    anatomy: ['Icon rail: modes', 'List panel owned by the active mode', 'Work area'],
    shines: [
      'Tools with a few modes that each own a list (files, search, history)',
      'Power users who learn the icons; maximum width for the work',
    ],
    avoid: ['Novices who need labels', 'More than about seven modes'],
    examples: [{ app: 'SDK', note: 'SidebarMenu collapsed to its rail; the rail pattern of code editors' }],
    related: ['sidebar-shell', 'studio-three-pane'],
    tags: ['rail', 'power-user'],
  },
  {
    id: 'studio-three-pane',
    name: 'Studio three-pane',
    summary: 'Navigator, work and inspector side by side — select, see, act without leaving.',
    spec: spec({ nav: 'top', leading: 'navigator', trailing: 'inspector', content: 'detail', surface: 'cards' }),
    anatomy: [
      'Navigator: the objects',
      'Work: the selected object and its state',
      'Inspector: the selected part and its actions',
    ],
    shines: [
      'A selected object with context, evidence and actions',
      'Operations and editing where the controls must sit beside their target',
    ],
    avoid: ['Narrow screens without a sheet fallback', 'Objects with nothing to inspect'],
    examples: [
      { app: 'Wheelhouse', note: 'Products and environments · environment work · target inspector' },
      { app: 'Ocharo', note: 'Material studio: library · material · preview card' },
    ],
    related: ['master-detail', 'canvas-docked', 'canvas-islands'],
    tags: ['workspace', 'inspector'],
  },
  {
    id: 'canvas-islands',
    name: 'Canvas + floating islands',
    summary: 'The canvas fills the frame; library, inspector and tools float over it as rounded islands.',
    spec: spec({
      nav: 'toolbar',
      leading: 'library',
      trailing: 'inspector',
      panelMode: 'floating',
      content: 'scene',
      surface: 'islands',
      density: 'spacious',
      bottomDock: true,
    }),
    anatomy: ['Full-bleed canvas', 'Library island', 'Inspector island', 'Tool island along the bottom'],
    shines: [
      'The canvas is the hero: 3D, maps, media, whiteboards',
      'Immersive and creative work with a few short panels at a time',
      'Brand and mood — the object never touches chrome',
    ],
    avoid: [
      'Long, data-heavy panels — they cover the work',
      'Heavy panning: content slides under the islands',
      'Many panels open at once',
    ],
    examples: [
      { app: 'Ocharo', note: 'Garment studio: library, part inspector and camera island around the mannequin' },
    ],
    related: ['canvas-docked', 'map-sheet', 'studio-three-pane'],
    tags: ['canvas', 'floating', 'creative'],
  },
  {
    id: 'canvas-docked',
    name: 'Canvas + docked console',
    summary: 'A toolbar across the top, the canvas, and a resizable docked inspector; small overlays in the corners.',
    spec: spec({ nav: 'toolbar', local: 'tabs', trailing: 'inspector', content: 'map', density: 'compact' }),
    anatomy: [
      'Toolbar with scenario tabs',
      'Canvas with corner overlays (zoom, legend)',
      'Docked, resizable, collapsible inspector',
    ],
    shines: [
      'Analysis where the panel is long and must never cover the canvas',
      'Power users who resize and collapse the dock',
    ],
    avoid: ['Casual users', 'Phones without a sheet'],
    examples: [{ app: 'TNIS', note: 'Map console: scenario tabs, full map, docked analysis accordion' }],
    related: ['canvas-islands', 'studio-three-pane'],
    tags: ['canvas', 'docked', 'analysis'],
  },
  {
    id: 'master-detail',
    name: 'Master–detail split',
    summary: 'A list pane and the selected record side by side, stepped through by keyboard.',
    spec: spec({ nav: 'side', leading: 'list', content: 'detail' }),
    anatomy: ['List of records', 'Selected record'],
    shines: ['Triage of many similar records', 'Keyboard stepping through a queue'],
    avoid: ['Records that need the full width', 'Phones — collapse to push navigation'],
    examples: [{ app: 'Wheelhouse', note: 'Deployment history beside the selected deployment' }],
    related: ['collection-drawer', 'inbox'],
    tags: ['split', 'triage'],
  },
  {
    id: 'collection-drawer',
    name: 'Collection + drawer',
    summary: 'The collection keeps the full width; a record opens in a drawer over it.',
    spec: spec({ nav: 'top', local: 'filters', trailing: 'detail', panelMode: 'overlay', content: 'grid' }),
    anatomy: ['Filters and view switch', 'Collection', 'Detail drawer on demand'],
    shines: ['Detail is occasional', 'The collection context must stay visible and restorable'],
    avoid: ['Long editing sessions in the drawer — promote them to a page', 'Side-by-side comparison'],
    examples: [{ app: 'Haven', note: 'Listing drawer over the CRM grid, table and board' }],
    related: ['master-detail', 'gallery', 'board'],
    tags: ['drawer', 'collection'],
  },
  {
    id: 'dashboard',
    name: 'Dashboard / bento',
    summary: 'A KPI row and a grid of tiles, each a doorway into its records.',
    spec: spec({ nav: 'side', content: 'dashboard', surface: 'cards' }),
    anatomy: ['KPI row', 'Chart tiles', 'A table tile with the records behind the numbers'],
    shines: ['Monitoring and overview', 'Glanceable status with a path into records'],
    avoid: ['Performing tasks', 'Dashboards of unrelated metrics'],
    examples: [{ app: 'Wheelhouse', note: 'Deployment outcomes and fleet vitals on the overview' }],
    related: ['data-console', 'top-bar-workspace'],
    tags: ['overview', 'monitoring'],
  },
  {
    id: 'board',
    name: 'Board (kanban)',
    summary: 'Columns by stage; cards move across as work progresses.',
    spec: spec({ nav: 'top', local: 'filters', content: 'kanban' }),
    anatomy: ['Filters shared with the list view', 'Stage columns', 'Compact cards'],
    shines: [
      'Flow work with stages and limited work in progress',
      'Status at a glance; moving work forward by dragging',
    ],
    avoid: ['More than a few dozen cards per column', 'Comparing attributes', 'Sorting on many axes'],
    examples: [{ app: 'Haven', note: 'Listing triage board beside the grid and table over one filter' }],
    related: ['data-console', 'gallery', 'collection-drawer'],
    tags: ['collection', 'flow'],
  },
  {
    id: 'gallery',
    name: 'Gallery grid',
    summary: 'Uniform cards where the image does the deciding.',
    spec: spec({ nav: 'top', local: 'filters', content: 'grid', surface: 'cards' }),
    anatomy: ['Filters', 'Media cards with a title and one or two facts'],
    shines: ['Visual recognition and comparison — photos, swatches, products'],
    avoid: ['Attribute-heavy comparison', 'Text-only items'],
    examples: [
      { app: 'Haven', note: 'Listing photo grid' },
      { app: 'Ocharo', note: 'Material library and landing gallery' },
    ],
    related: ['board', 'data-console'],
    tags: ['collection', 'visual'],
  },
  {
    id: 'data-console',
    name: 'Data console',
    summary: 'Filters, a dense table, a bulk bar and pagination.',
    spec: spec({ nav: 'side', local: 'filters', content: 'table', density: 'compact' }),
    anatomy: ['Toolbar with filters and search', 'Dense sortable table', 'Bulk bar and pagination'],
    shines: ['Many attributes', 'Sorting, filtering and bulk operations'],
    avoid: ['Casual browsing', 'Visual items'],
    examples: [{ app: 'Haven', note: 'Compact listing table with bulk publish' }],
    related: ['board', 'gallery', 'dashboard'],
    tags: ['collection', 'dense'],
  },
  {
    id: 'docs',
    name: 'Docs / reading',
    summary: 'Section navigation, the article, and an on-this-page outline.',
    spec: spec({ nav: 'top', leading: 'navigator', trailing: 'toc', content: 'article', density: 'spacious' }),
    anatomy: ['Section navigation', 'Article with a readable measure', 'On-this-page outline'],
    shines: ['Long-form reading, reference and learning'],
    avoid: ['Task-driven apps'],
    examples: [{ app: 'Atlas', note: 'This site' }],
    related: ['settings', 'feed'],
    tags: ['reading'],
  },
  {
    id: 'settings',
    name: 'Settings',
    summary: 'A list of sections beside grouped forms.',
    spec: spec({ nav: 'side', leading: 'sections', content: 'form' }),
    anatomy: ['Section list', 'Grouped form with inline help', 'Save or autosave feedback'],
    shines: ['Many independent preferences'],
    avoid: ['Linear tasks — use a wizard'],
    examples: [{ app: 'SDK', note: 'Field, FieldsetLayout and FormField compose the groups' }],
    related: ['wizard', 'sidebar-shell'],
    tags: ['form'],
  },
  {
    id: 'wizard',
    name: 'Wizard',
    summary: 'One task per screen with visible steps and a steady footer.',
    spec: spec({ nav: 'none', local: 'steps', content: 'form', density: 'spacious' }),
    anatomy: ['Steps', 'One task', 'Back and continue'],
    shines: ['Linear tasks with dependencies', 'Onboarding'],
    avoid: ['Expert repeat work — a single form is faster'],
    examples: [{ app: 'SDK', note: 'WizardForm and StepperGroup' }],
    related: ['settings', 'landing'],
    tags: ['flow', 'form'],
  },
  {
    id: 'inbox',
    name: 'Inbox / chat',
    summary: 'Conversations, the open thread, and its context.',
    spec: spec({ nav: 'rail', leading: 'list', trailing: 'context', content: 'chat', density: 'compact' }),
    anatomy: ['Conversation list', 'Thread with composer', 'Context about the person or ticket'],
    shines: ['Messaging and support queues'],
    avoid: ['Records that are not conversations'],
    examples: [{ app: 'SDK', note: 'ChatBubble, MessageList, ChatComposerInput, MentionInput' }],
    related: ['master-detail', 'feed'],
    tags: ['conversation'],
  },
  {
    id: 'feed',
    name: 'Feed',
    summary: 'A single readable column of updates with context beside it.',
    spec: spec({ nav: 'top', trailing: 'context', content: 'feed' }),
    anatomy: ['Chronological stream', 'Context and filters'],
    shines: ['Activity and chronological updates'],
    avoid: ['Comparison or bulk work'],
    examples: [{ app: 'SDK', note: 'ActivityFeed and ActivityTimeline' }],
    related: ['docs', 'inbox'],
    tags: ['stream'],
  },
  {
    id: 'mobile-tabs',
    name: 'Mobile tab app',
    summary: 'A title, the screen, and three to five peer destinations in a bottom bar.',
    spec: spec({ nav: 'bottom', content: 'list' }),
    anatomy: ['Title bar', 'Screen', 'Bottom tab bar'],
    shines: ['Phone-first products with a few peer destinations'],
    avoid: ['More than five destinations', 'Desktop-only tools'],
    examples: [{ app: 'SDK', note: 'BottomNavMenu with badges and router links' }],
    related: ['map-sheet', 'top-bar-workspace'],
    tags: ['mobile'],
  },
  {
    id: 'map-sheet',
    name: 'Map + bottom sheet',
    summary: 'The map fills the phone; details rise in a draggable sheet.',
    spec: spec({ nav: 'none', trailing: 'detail', panelMode: 'floating', content: 'map', surface: 'islands' }),
    anatomy: ['Full map', 'Floating search', 'Sheet with snap points'],
    shines: ['Location-first phone apps'],
    avoid: ['Desktop analysis — use the docked console'],
    examples: [{ app: 'TNIS', note: 'Rider surface on the same map data' }],
    related: ['canvas-docked', 'canvas-islands', 'mobile-tabs'],
    tags: ['canvas', 'mobile'],
  },
  {
    id: 'landing',
    name: 'Landing',
    summary: 'A hero, feature sections and one clear call to action.',
    spec: spec({ nav: 'top', content: 'hero', density: 'spacious', surface: 'flat' }),
    anatomy: ['Hero with the product itself', 'Feature sections', 'Call to action'],
    shines: ['Marketing and onboarding into an app'],
    avoid: ['The working app itself — keep promotion out of the editor'],
    examples: [{ app: 'Ocharo', note: 'Editorial landing separate from the studio' }],
    related: ['wizard', 'gallery'],
    tags: ['marketing'],
  },
];

/** Finds an archetype by id. */
export function findArchetype(id: string | null): Archetype | undefined {
  return Archetypes.find((archetype) => archetype.id === id);
}
