/* ---------------------------------------------------------------------------
 * CSS emitter — turn a Theme into scoped class blocks.
 *
 * An app applies a theme by adding `theme-{id}` to a root element. The emitted
 * CSS overrides the lib's semantic `--color-*` vars (and optional `--radius-*`)
 * under that class, so every Tailwind utility (`bg-primary`, `text-foreground`,
 * …) re-resolves to the theme's values. Dark mode reuses the lib's variant:
 * `.dark.theme-{id}` (i.e. `.dark` + the theme class on the same element, or an
 * ancestor `.dark`).
 * ------------------------------------------------------------------------- */

import type { Theme, ThemeStatus } from './Theme';
import { SEMANTIC_TOKENS, type TokenSet } from './Tokens';

/** Radius knob → concrete `--radius-*` triple (mirrors the lib's default scale shifts). */
const RADIUS_SCALE: Record<NonNullable<Theme['radius']>, Record<string, string>> = {
  sm: { md: '0.375rem', lg: '0.5rem', xl: '0.75rem' },
  md: { md: '0.5rem', lg: '0.75rem', xl: '1rem' },
  lg: { md: '0.625rem', lg: '0.875rem', xl: '1.25rem' },
};

/** Render one token set as `  --color-{key}: {value};` declaration lines. */
function declarations(set: TokenSet, indent = '  '): string {
  return SEMANTIC_TOKENS.map((tok) => `${indent}--color-${tok}: ${set[tok]};`).join(
    '\n',
  );
}

/** Render the optional radius overrides as declaration lines (empty string when unset). */
function radiusDeclarations(theme: Theme, indent = '  '): string {
  if (!theme.radius) return '';
  const scale = RADIUS_SCALE[theme.radius];
  return (
    '\n' +
    Object.entries(scale)
      .map(([k, v]) => `${indent}--radius-${k}: ${v};`)
      .join('\n')
  );
}

/**
 * Emit the CSS for a single theme: a light `.theme-{id}` block + a
 * `.dark.theme-{id}` block. Returns a string (no trailing newline).
 */
export function themeToCss(theme: Theme): string {
  const radius = radiusDeclarations(theme);
  const light = `.theme-${theme.id} {\n${declarations(theme.light)}${radius}\n}`;
  const dark = `.dark.theme-${theme.id} {\n${declarations(theme.dark)}\n}`;
  return `${light}\n\n${dark}`;
}

/** Emit a full stylesheet for many themes, with a generated-file banner. */
export function emitAllThemesCss(themes: Theme[]): string {
  const banner =
    '/* Generated by @wow-two-beta/ui theme engine — do not edit by hand.\n' +
    ' * Source: src/themes/registry.ts → regenerate via the package build. */\n';
  const body = themes.map(themeToCss).join('\n\n');
  return `${banner}\n${body}\n`;
}

/** Machine-readable manifest entry for one theme (no token payload — index only). */
export interface ThemeManifestEntry {
  id: string;
  name: string;
  description: string;
  tags: string[];
  /** Lifecycle status — `validated` (real-app proven) or `candidate` (engine-proven). */
  status: ThemeStatus;
  contrastAA: boolean;
}

/** Build the `themes.json` manifest payload from the registry. */
export function emitThemesManifest(themes: Theme[]): ThemeManifestEntry[] {
  return themes.map((t) => ({
    id: t.id,
    name: t.name,
    description: t.description,
    tags: t.tags,
    status: t.status,
    contrastAA: t.meta.contrastAA,
  }));
}
