import { defineConfig } from 'tsup';

// Component group -> physical layer folder under `src/`. Public subpaths are now
// layer-prefixed (`@wow-two-beta/ui/<layer>/<group>`) and `dist/` mirrors the
// layers 1:1 (`dist/<layer>/<group>/index.*`). Keep in sync with `package.json`
// exports and `apps/lib-source-alias.mjs`.
const subpathLayer: Record<string, 'foundation' | 'domain' | 'presentation'> = {
  utils: 'foundation',
  hooks: 'foundation',
  icons: 'foundation',
  primitives: 'foundation',
  themes: 'foundation',
  http: 'foundation',
  storage: 'foundation',
  resilience: 'foundation',
  color: 'domain',
  emoji: 'domain',
  actions: 'presentation',
  display: 'presentation',
  feedback: 'presentation',
  forms: 'presentation',
  layout: 'presentation',
  nav: 'presentation',
  overlays: 'presentation',
};

export default defineConfig({
  entry: {
    index: 'src/index.ts',
    // `router` is a standalone top-level subpath (`@wow-two-beta/ui/router`), not layer-prefixed like
    // the component groups below — this keeps its react-router-dom peer dep out of every other entry.
    'router/index': 'src/router/index.ts',
    // `query` mirrors `router` — a standalone top-level subpath (`@wow-two-beta/ui/query`) whose
    // optional `@tanstack/react-query` peer stays out of every other entry. `query/testing` is a
    // second entry for the test-only helpers (`@wow-two-beta/ui/query/testing`).
    'query/index': 'src/query/index.ts',
    'query/testing': 'src/query/testing.ts',
    // Entry KEY = dist path (`dist/<layer>/<group>/index.js`) — mirrors the
    // layered source folder so the emitted subpath matches the public export.
    ...Object.fromEntries(
      Object.entries(subpathLayer).map(([group, layer]) => [
        `${layer}/${group}/index`,
        `src/${layer}/${group}/index.ts`,
      ]),
    ),
  },
  format: ['esm'],
  banner: { js: '"use client";' }, // whole lib is client-side — keep chunks importable from RSC
  dts: false, // generated by `tsc --emitDeclarationOnly` to avoid rollup-plugin-dts ENFILE issues on macOS
  clean: true,
  sourcemap: true,
  treeshake: true,
  external: [
    'react',
    'react-dom',
    'react-router-dom',
    // Query subpath peers — kept external so `@wow-two-beta/ui/query` carries no bundled RQ and the
    // root/other entries stay RQ-free. `@testing-library/react` (a devDep) is external only so the
    // `query/testing` entry references it rather than inlining it.
    '@tanstack/react-query',
    '@tanstack/react-query-persist-client',
    '@tanstack/query-sync-storage-persister',
    '@tanstack/react-query-devtools',
    '@testing-library/react',
  ],
});
