import { defineConfig } from 'tsup';

const folders = [
  'utils',
  'hooks',
  'icons',
  'primitives',
  'actions',
  'display',
  'feedback',
  'forms',
  'layout',
];

export default defineConfig({
  entry: {
    index: 'src/index.ts',
    ...Object.fromEntries(folders.map((f) => [`${f}/index`, `src/${f}/index.ts`])),
  },
  format: ['esm'],
  dts: false, // generated by `tsc --emitDeclarationOnly` to avoid rollup-plugin-dts ENFILE issues on macOS
  clean: true,
  sourcemap: true,
  treeshake: true,
  external: ['react', 'react-dom'],
});
