import { defineConfig } from 'tsup';

// Component group -> physical layer folder under `src/`. Public subpaths are now
// layer-prefixed (`@wow-two-beta/ui/<layer>/<group>`) and `dist/` mirrors the
// layers 1:1 (`dist/<layer>/<group>/index.*`). Keep in sync with `package.json`
// exports and `apps/lib-source-alias.mjs`.
const subpathLayer: Record<string, 'foundation' | 'domain' | 'presentation'> = {
  utils: 'foundation',
  hooks: 'foundation',
  icons: 'foundation',
  primitives: 'foundation',
  themes: 'foundation',
  http: 'foundation',
  color: 'domain',
  actions: 'presentation',
  display: 'presentation',
  feedback: 'presentation',
  forms: 'presentation',
  layout: 'presentation',
  nav: 'presentation',
  overlays: 'presentation',
};

export default defineConfig({
  entry: {
    index: 'src/index.ts',
    // Entry KEY = dist path (`dist/<layer>/<group>/index.js`) — mirrors the
    // layered source folder so the emitted subpath matches the public export.
    ...Object.fromEntries(
      Object.entries(subpathLayer).map(([group, layer]) => [
        `${layer}/${group}/index`,
        `src/${layer}/${group}/index.ts`,
      ]),
    ),
  },
  format: ['esm'],
  banner: { js: '"use client";' }, // whole lib is client-side — keep chunks importable from RSC
  dts: false, // generated by `tsc --emitDeclarationOnly` to avoid rollup-plugin-dts ENFILE issues on macOS
  clean: true,
  sourcemap: true,
  treeshake: true,
  external: ['react', 'react-dom'],
});
