export {
  Table,
  TableHead,
  TableBody,
  TableFooter,
  TableRow,
  TableHeaderCell,
  TableCell,
  TableCaption,
  type TableProps,
  type TableHeadProps,
  type TableHeaderCellProps,
  type TableCellProps,
  type TableDensity,
  type TableRadius,
  type TableHeadVariant,
} from './Table';
