import { h, type VNode } from 'vue';
import {
  Calendar,
  CharacterCount,
  Checkbox,
  CheckboxField,
  CheckboxGroup,
  ChoiceCard,
  ColorArea,
  ColorField,
  ColorPicker,
  ColorSlider,
  ColorSwatch,
  ColorSwatchPicker,
  ColorWheel,
  CurrencyInput,
  DateField,
  DatePicker,
  DateRangePicker,
  DateTimeField,
  EmailInput,
  EmojiPicker,
  EmojiPickerPopover,
  EmojiSizeControl,
  Field,
  Fieldset,
  FilePicker,
  FormErrorMessage,
  FormField,
  FormHelperText,
  InputAddon,
  InputGroup,
  Label,
  LabeledInput,
  Legend,
  Listbox,
  ListboxEmpty,
  ListboxGroup,
  ListboxItem,
  ListboxSeparator,
  MaskedInput,
  NumberInput,
  PasswordInput,
  PasswordStrength,
  PercentInput,
  PinInput,
  Radio,
  RadioField,
  RadioGroup,
  RangeCalendar,
  ReactionPicker,
  SearchInput,
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
  Slider,
  Switch,
  SwitchField,
  TagsInput,
  TelInput,
  TextAreaInput,
  TextInput,
  TimeField,
  TimePicker,
  UrlInput,
} from '@src/presentation/forms';
import { memoryStorageBroker } from '@src/foundation/storage';
import { smokeCase, type SmokeCase } from '../../../support/Smoke';

/* Wrappers for the compound parts — each renders the part inside the root whose `provide` it
   injects. Both roots are opened through their UNCONTROLLED path (`defaultOpen`), never by
   passing `isOpen`, which doubles as the guard for the port's `boolean` cast bug. */
const inListbox = (node: VNode): VNode => h(Listbox, null, () => node);

/* Select declares a required `default` slot, so its children go in as a slots object — the
   bare-function children form does not satisfy that. */
const inSelect = (node: VNode): VNode =>
  h(Select, { defaultOpen: true }, { default: () => node });
const inSelectTrigger = (node: VNode): VNode => inSelect(h(SelectTrigger, null, () => node));
const inSelectContent = (node: VNode): VNode => inSelect(h(SelectContent, null, () => node));


/**
 * Every component `@wow-two-beta/ui-vue/presentation/forms` exports, as smoke cases.
 * Imported through the public barrel on purpose — a component missing from `index.ts` fails
 * here before a consumer finds it.
 */
export const formsCases: readonly SmokeCase[] = [
  smokeCase('Label', Label, {}, { slot: true }),
  smokeCase('FormHelperText', FormHelperText, {}, { slot: true }),
  smokeCase('FormErrorMessage', FormErrorMessage, {}, { slot: true }),
  smokeCase('Fieldset', Fieldset, {}, { slot: true }),
  smokeCase('Legend', Legend, {}, { slot: true }),
  smokeCase('TextInput', TextInput, {}),
  smokeCase('EmailInput', EmailInput, {}),
  smokeCase('TelInput', TelInput, {}),
  smokeCase('UrlInput', UrlInput, {}),
  smokeCase('NumberInput', NumberInput, {}),
  smokeCase('PasswordInput', PasswordInput, {}),
  smokeCase('SearchInput', SearchInput, {}),
  smokeCase('TextAreaInput', TextAreaInput, {}),
  smokeCase('Checkbox', Checkbox, {}),
  smokeCase('Radio', Radio, {}),
  smokeCase('Switch', Switch, {}),
  smokeCase('Slider', Slider, {}),
  smokeCase('Field', Field, {}, { slot: true }),
  smokeCase('FormField', FormField, {}, { slot: true }),
  smokeCase('CheckboxField', CheckboxField, {}),
  smokeCase('RadioField', RadioField, {}),
  smokeCase('SwitchField', SwitchField, {}),
  smokeCase('CheckboxGroup', CheckboxGroup, {}, { slot: true }),
  smokeCase('RadioGroup', RadioGroup, {}, { slot: true }),
  smokeCase('PinInput', PinInput, {}),
  smokeCase('MaskedInput', MaskedInput, { mask: '999-999' }),
  smokeCase('CurrencyInput', CurrencyInput, {}),
  smokeCase('PercentInput', PercentInput, {}),
  smokeCase('CharacterCount', CharacterCount, { value: 3, max: 10 }),
  smokeCase('InputAddon', InputAddon, {}, { slot: true }),
  smokeCase('InputGroup', InputGroup, {}, { slot: true }),
  smokeCase('LabeledInput', LabeledInput, {}, { slot: true }),
  smokeCase('ChoiceCard', ChoiceCard, {}),
  smokeCase('PasswordStrength', PasswordStrength, { value: 'hunter2' }),
  smokeCase('FilePicker', FilePicker, {}),
  smokeCase('Listbox', Listbox, {}, { slot: true }),
  smokeCase('ListboxItem', ListboxItem, { value: 'one' }, { slot: true, wrap: inListbox }),
  smokeCase('ListboxGroup', ListboxGroup, {}, { slot: true, wrap: inListbox }),
  smokeCase('ListboxSeparator', ListboxSeparator, {}, { wrap: inListbox }),
  smokeCase('ListboxEmpty', ListboxEmpty, {}, { slot: true, wrap: inListbox }),
  smokeCase('Select', Select, {}, { slot: true }),
  smokeCase('SelectTrigger', SelectTrigger, {}, { slot: true, wrap: inSelect }),
  smokeCase('SelectValue', SelectValue, {}, { slot: true, wrap: inSelectTrigger }),
  smokeCase('SelectContent', SelectContent, {}, { slot: true, wrap: inSelect }),
  smokeCase('SelectItem', SelectItem, { itemKey: 'one', label: 'One' }, { slot: true, wrap: inSelectContent }),
  smokeCase('Calendar', Calendar, {}),
  smokeCase('DateField', DateField, {}),
  smokeCase('DateTimeField', DateTimeField, {}),
  smokeCase('TimeField', TimeField, {}),
  smokeCase('RangeCalendar', RangeCalendar, {}),
  smokeCase('DatePicker', DatePicker, {}),
  smokeCase('TimePicker', TimePicker, {}),
  smokeCase('DateRangePicker', DateRangePicker, {}),
  smokeCase('ColorSwatch', ColorSwatch, {}),
  smokeCase('ColorField', ColorField, {}),
  smokeCase('ColorSlider', ColorSlider, {}),
  smokeCase('ColorArea', ColorArea, {}),
  smokeCase('ColorWheel', ColorWheel, {}),
  smokeCase('ColorSwatchPicker', ColorSwatchPicker, { colors: ['#ff0000', '#00ff00'] }),
  smokeCase('ColorPicker', ColorPicker, {}),
  smokeCase('TagsInput', TagsInput, {}),
  smokeCase('EmojiPicker', EmojiPicker, { storage: memoryStorageBroker() }),
  smokeCase('EmojiPickerPopover', EmojiPickerPopover, { storage: memoryStorageBroker() }),
  smokeCase('EmojiSizeControl', EmojiSizeControl, { glyph: '\u{1F600}' }),
  smokeCase('ReactionPicker', ReactionPicker, {}),
];
