/* Authored palettes.
 * Smart QR: brand fills and neutral backgrounds preserve the original app colors; foreground tokens were corrected
 * for the SDK's declared text/placeholder/glass contrast pairs and await visual review in the app.
 * Ocharo: the Ocharo Studio palette (paper, linen, green-slate ink, pomegranate) with harmonised status tones.
 * Both are candidates until a shipping app validates them through the registry. */

import type { Theme } from '../Theme';
import { ThemeRadius, ThemeStatus } from '../Theme';
import type { TokenSet } from '../Tokens';
import { validateTheme } from '../Validate';

// Original inherited palette retained as the authored base; explicit foreground corrections follow below.
const SmartQrBaseLight: TokenSet = {
  background: '#ffffff',
  foreground: '#18181b',
  card: '#ffffff',
  'card-foreground': '#18181b',
  popover: '#ffffff',
  'popover-foreground': '#18181b',
  muted: '#f4f4f5',
  'muted-foreground': '#71717a',
  'subtle-foreground': '#a1a1aa',
  inverse: '#18181b',
  'inverse-foreground': '#fafafa',
  border: '#e4e4e7',
  'border-strong': '#d4d4d8',
  input: '#d4d4d8',
  ring: '#3b82f6',
  primary: '#2563eb',
  'primary-foreground': '#ffffff',
  'primary-soft': '#dbeafe',
  'primary-soft-foreground': '#1d4ed8',
  accent: '#0d9488',
  'accent-foreground': '#ffffff',
  'accent-soft': '#ccfbf1',
  'accent-soft-foreground': '#115e59',
  destructive: '#dc2626',
  'destructive-foreground': '#ffffff',
  'destructive-soft': '#fef2f2',
  'destructive-soft-foreground': '#b91c1c',
  info: '#0891b2',
  'info-foreground': '#ffffff',
  'info-soft': '#ecfeff',
  'info-soft-foreground': '#0e7490',
  success: '#16a34a',
  'success-foreground': '#ffffff',
  'success-soft': '#f0fdf4',
  'success-soft-foreground': '#15803d',
  warning: '#f59e0b',
  'warning-foreground': '#78350f',
  'warning-soft': '#fffbeb',
  'warning-soft-foreground': '#b45309',
};

const SmartQrBaseDark: TokenSet = {
  background: '#09090b',
  foreground: '#fafafa',
  card: '#18181b',
  'card-foreground': '#fafafa',
  popover: '#18181b',
  'popover-foreground': '#fafafa',
  muted: '#18181b',
  'muted-foreground': '#a1a1aa',
  'subtle-foreground': '#71717a',
  inverse: '#fafafa',
  'inverse-foreground': '#09090b',
  border: '#27272a',
  'border-strong': '#3f3f46',
  input: '#3f3f46',
  ring: '#60a5fa',
  primary: '#3b82f6',
  'primary-foreground': '#ffffff',
  'primary-soft': '#1e3a8a',
  'primary-soft-foreground': '#dbeafe',
  accent: '#2dd4bf',
  'accent-foreground': '#042f2e',
  'accent-soft': '#134e4a',
  'accent-soft-foreground': '#5eead4',
  destructive: '#ef4444',
  'destructive-foreground': '#ffffff',
  'destructive-soft': '#7f1d1d',
  'destructive-soft-foreground': '#fee2e2',
  info: '#06b6d4',
  'info-foreground': '#ffffff',
  'info-soft': '#164e63',
  'info-soft-foreground': '#cffafe',
  success: '#22c55e',
  'success-foreground': '#ffffff',
  'success-soft': '#14532d',
  'success-soft-foreground': '#dcfce7',
  warning: '#f59e0b',
  'warning-foreground': '#78350f',
  'warning-soft': '#78350f',
  'warning-soft-foreground': '#fef3c7',
};

// Original authored backgrounds and brand fills; foreground corrections are explicit and reviewable.
const smartQrLight: TokenSet = {
  ...SmartQrBaseLight,
  background: '#d9dde8',
  card: '#ebeef4',
  popover: '#ebeef4',
  'popover-foreground': '#1c1d26',
  muted: '#f1f2f8',
  foreground: '#1c1d26',
  'card-foreground': '#1c1d26', // = foreground (app inherits foreground here)
  'muted-foreground': 'oklch(49.6% 0.0358 279.3)',
  'subtle-foreground': 'oklch(49.5% 0.0323 277.4)',
  border: '#e4e6f0',
  'border-strong': 'oklch(59.1% 0.0210 276.9)',
  input: 'oklch(59.0% 0.0137 277.1)',
  ring: '#8b5cf6',
  primary: '#7c3aed',
  'primary-foreground': '#f5f3ff',
  'primary-soft': '#ede9fe',
  'primary-soft-foreground': 'oklch(42.5% 0.2106 292.8)',
  accent: '#0d9488',
  'accent-foreground': 'oklch(22.9% 0.0000 89.9)',
  'accent-soft': '#ccfbf1',
  'accent-soft-foreground': 'oklch(41.6% 0.0705 188.2)',
  'destructive-soft-foreground': 'oklch(41.4% 0.1694 27.5)',
  'info-foreground': 'oklch(23.5% 0.0000 89.9)',
  'info-soft-foreground': 'oklch(41.9% 0.0783 223.1)',
  'success-foreground': 'oklch(27.3% 0.0000 89.9)',
  'success-soft-foreground': 'oklch(41.8% 0.1152 150.1)',
  'warning-foreground': 'oklch(39.7% 0.1054 45.9)',
  'warning-soft-foreground': 'oklch(46.9% 0.1261 49.0)',
};

const smartQrDark: TokenSet = {
  ...SmartQrBaseDark,
  background: '#121214',
  card: '#1c1c1f',
  popover: '#1c1c1f',
  'popover-foreground': '#e7e7e9',
  muted: '#18181b',
  foreground: '#e7e7e9',
  'card-foreground': '#e7e7e9', // = foreground (app inherits foreground here)
  'muted-foreground': '#a1a1aa',
  'subtle-foreground': 'oklch(61.3% 0.0123 286.0)',
  border: '#2a2a2e',
  'border-strong': 'oklch(51.6% 0.0103 285.9)',
  input: 'oklch(51.6% 0.0072 285.9)',
  ring: '#8b5cf6',
  primary: '#8b5cf6',
  'primary-soft': '#2a2440',
  'primary-soft-foreground': '#c4b5fd',
  accent: '#2dd4bf',
  'accent-soft': '#103a35',
  'accent-soft-foreground': '#5eead4',
  'primary-foreground': 'oklch(16.9% 0.0000 89.9)',
  'destructive-foreground': 'oklch(22.7% 0.0000 89.9)',
  'info-foreground': 'oklch(35.7% 0.0000 89.9)',
  'success-foreground': 'oklch(37.3% 0.0000 89.9)',
  'warning-foreground': 'oklch(39.7% 0.1054 45.9)',
};

/** Smart QR with contrast-corrected foregrounds, awaiting a fresh visual review in the app. */
const smartQr: Theme = {
  id: 'smart-qr',
  name: 'Smart QR',
  description:
    'Violet brand + teal accent on cool lavender-grey (light) / charcoal (dark) — contrast-corrected Smart QR candidate awaiting app review.',
  tags: ['brand', 'violet', 'teal', 'candidate', 'aa', 'product'],
  light: smartQrLight,
  dark: smartQrDark,
  status: ThemeStatus.Candidate,
  meta: validateTheme({ light: smartQrLight, dark: smartQrDark }),
};

// Ocharo Studio light: warm paper and linen surfaces, green-slate ink, pomegranate brand.
const ocharoLight: TokenSet = {
  background: '#f1f0eb',
  foreground: '#303b37',
  card: '#fffefa',
  'card-foreground': '#303b37',
  popover: '#fffefa',
  'popover-foreground': '#303b37',
  muted: '#f5f5ef',
  'muted-foreground': '#596259',
  'subtle-foreground': '#5f675f',
  inverse: '#303b37',
  'inverse-foreground': '#fffefa',
  border: '#e7e7df',
  'border-strong': '#7f877f',
  input: '#7f877f',
  ring: '#7a3944',
  primary: '#7a3944',
  'primary-foreground': '#fffefa',
  'primary-soft': '#f6e9e9',
  'primary-soft-foreground': '#6c3039',
  accent: '#4a6356',
  'accent-foreground': '#fffefa',
  'accent-soft': '#e7eee9',
  'accent-soft-foreground': '#3a5045',
  destructive: '#a8322d',
  'destructive-foreground': '#fffefa',
  'destructive-soft': '#f8e6e3',
  'destructive-soft-foreground': '#8e2a26',
  info: '#2f5f86',
  'info-foreground': '#fffefa',
  'info-soft': '#e5eef5',
  'info-soft-foreground': '#264f6f',
  success: '#2f6a47',
  'success-foreground': '#fffefa',
  'success-soft': '#e4f0e8',
  'success-soft-foreground': '#255638',
  warning: '#8a5a0a',
  'warning-foreground': '#fffefa',
  'warning-soft': '#f7ecd8',
  'warning-soft-foreground': '#6c4506',
};

// Ocharo Studio dark: deep green-slate surfaces, pale linen ink, rose brand.
const ocharoDark: TokenSet = {
  background: '#242b29',
  foreground: '#eceee5',
  card: '#303835',
  'card-foreground': '#eceee5',
  popover: '#303835',
  'popover-foreground': '#eceee5',
  muted: '#39423d',
  'muted-foreground': '#b8c1b5',
  'subtle-foreground': '#aeb7ab',
  inverse: '#eceee5',
  'inverse-foreground': '#242b29',
  border: '#46504a',
  'border-strong': '#86918a',
  input: '#86918a',
  ring: '#daa0aa',
  primary: '#daa0aa',
  'primary-foreground': '#2a1c1f',
  'primary-soft': '#4d3c40',
  'primary-soft-foreground': '#f6dde1',
  accent: '#a9c4b4',
  'accent-foreground': '#1c2621',
  'accent-soft': '#344640',
  'accent-soft-foreground': '#dcebe1',
  destructive: '#f0968d',
  'destructive-foreground': '#3a0f0c',
  'destructive-soft': '#4f2f2d',
  'destructive-soft-foreground': '#fbdad6',
  info: '#93bddf',
  'info-foreground': '#0f2233',
  'info-soft': '#2c3f4d',
  'info-soft-foreground': '#cfe3f2',
  success: '#93cda9',
  'success-foreground': '#0f2a1a',
  'success-soft': '#2c4236',
  'success-soft-foreground': '#d6f0df',
  warning: '#e3b660',
  'warning-foreground': '#2e1f00',
  'warning-soft': '#4a3d25',
  'warning-soft-foreground': '#f8e6c1',
};

/** Ocharo Studio's palette as a theme; its island layout and typography stay in the product. */
const ocharo: Theme = {
  id: 'ocharo',
  name: 'Ocharo',
  description:
    'Pomegranate brand and sage accent on warm paper and linen (light) / deep green-slate (dark) — authored from Ocharo Studio.',
  tags: ['brand', 'pomegranate', 'sage', 'warm', 'paper', 'candidate', 'aa', 'product'],
  light: ocharoLight,
  dark: ocharoDark,
  radius: ThemeRadius.Lg,
  status: ThemeStatus.Candidate,
  meta: validateTheme({ light: ocharoLight, dark: ocharoDark }),
};

/** Authored palettes, merged before generated candidates in the registry. */
export const AuthoredThemes: ReadonlyArray<Theme> = [smartQr, ocharo];
