import { h, type VNode } from 'vue';
import { Temporal } from 'temporal-polyfill';
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
  ActivityFeed,
  ActivityItem,
  AnimatedNumber,
  AnnotationMarker,
  AudioPlayer,
  AudioWaveform,
  Avatar,
  AvatarGroup,
  Badge,
  BadgeOverlay,
  Card,
  CardBody,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
  Carousel,
  CarouselDot,
  CarouselDots,
  CarouselNext,
  CarouselPrev,
  CarouselSlide,
  CarouselSlides,
  CarouselViewport,
  CellsGlyph,
  ChatBubble,
  Code,
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger,
  Comment,
  CommentThread,
  Confetti,
  CountBadge,
  CountUp,
  DataGrid,
  DataTable,
  DaySeparator,
  DescriptionList,
  DiffViewer,
  DotsGlyph,
  EmptyState,
  EventCalendar,
  Eyebrow,
  FeatureCard,
  FrameGlyph,
  Gantt,
  GradientText,
  Heading,
  HeatmapCalendar,
  Highlight,
  HorizontalBarsGlyph,
  Image,
  InfoRow,
  Kbd,
  KeyboardShortcut,
  List,
  ListItem,
  Mark,
  Marquee,
  MessageList,
  MetaInline,
  MetricChip,
  NodeEditor,
  NotificationDot,
  PDFViewer,
  PricingCard,
  Quote,
  RadiusGlyph,
  ReactionBar,
  ScheduleView,
  ScrollReveal,
  SectionHeader,
  Separator,
  Snippet,
  Sortable,
  SortableHandle,
  SortableItem,
  Sparkline,
  Stat,
  Status,
  StepCard,
  SwipeActions,
  Table,
  TableBody,
  TableCaption,
  TableCell,
  TableFooter,
  TableHead,
  TableHeaderCell,
  TableRow,
  Tabs,
  TabsList,
  TabsPanel,
  TabsTab,
  Tag,
  Text,
  ThreadView,
  Tilt,
  Timeline,
  TimelineDescription,
  TimelineItem,
  TimelineTitle,
  Tooltip,
  Tree,
  TreeGroup,
  TreeItem,
  Typewriter,
  VerticalBarsGlyph,
  VideoPlayer,
} from '@src/presentation/display';
import { smokeCase, type SmokeCase } from '../../../support/Smoke';

/* One task is enough to exercise the whole Gantt render path — the tier asks whether it renders
   at all, not whether the bars land in the right columns. */
const ganttTask = {
  id: 't1',
  label: 'Port the SDK',
  start: Temporal.PlainDate.from('2026-01-05'),
  end: Temporal.PlainDate.from('2026-01-09'),
};

/* DataGrid is generic over its row. `PropsOf` instantiates that type parameter at its
   constraint, so the row arrives as `unknown` here and the narrowing has to be explicit — the
   generic cannot be recovered from a conditional type. The cast is confined to these two
   callbacks; everything else about the case is still fully checked. */
interface GridRow {
  id: string;
  name: string;
}

const gridRows: readonly GridRow[] = [{ id: 'r1', name: 'Ada' }];

/* Wrappers for the compound parts — each renders the part inside the root whose `provide` it
   injects, so the part is smoke-tested in the shape it actually ships in. */
const inCollapsible = (node: VNode): VNode => h(Collapsible, { defaultOpen: true }, () => node);

const inAccordion = (node: VNode): VNode => h(Accordion, { defaultValue: 'item-1' }, () => node);

const inAccordionItem = (node: VNode): VNode => inAccordion(h(AccordionItem, { value: 'item-1' }, () => node));

const inTabs = (node: VNode): VNode => h(Tabs, { defaultValue: 'tab-1' }, () => node);
const inTabsList = (node: VNode): VNode => inTabs(h(TabsList, null, () => node));

const inTree = (node: VNode): VNode => h(Tree, null, () => node);
/* TreeGroup renders its children inside `Presence :is-present="isExpanded"`, so the branch has
   to start expanded for the slot to exist at all. */
const inExpandedTree = (node: VNode): VNode => h(Tree, { defaultExpanded: ['group-1'] }, () => node);

const inCarousel = (node: VNode): VNode => h(Carousel, null, () => node);
const inCarouselViewport = (node: VNode): VNode => inCarousel(h(CarouselViewport, null, () => node));

const inSortable = (node: VNode): VNode => h(Sortable, null, () => node);
const inSortableItem = (node: VNode): VNode => inSortable(h(SortableItem, { index: 0 }, () => node));

/**
 * Every component `@wow-two-beta/ui-vue/presentation/display` exports, as smoke cases.
 * Imported through the public barrel on purpose — a component missing from `index.ts` fails
 * here before a consumer finds it.
 */
export const displayCases: readonly SmokeCase[] = [
  smokeCase('Heading', Heading, {}, { slot: true }),
  smokeCase('Text', Text, {}, { slot: true }),
  smokeCase('Code', Code, {}, { slot: true }),
  smokeCase('Kbd', Kbd, {}, { slot: true }),
  smokeCase('Image', Image, {}),
  smokeCase('Avatar', Avatar, {}),
  smokeCase('Badge', Badge, {}, { slot: true }),
  smokeCase('Tag', Tag, {}, { slot: true }),
  smokeCase('Separator', Separator, {}),
  smokeCase('Mark', Mark, {}, { slot: true }),
  smokeCase('Quote', Quote, {}, { slot: true }),
  smokeCase('Card', Card, {}, { slot: true }),
  smokeCase('CardHeader', CardHeader, {}, { slot: true }),
  smokeCase('CardTitle', CardTitle, {}, { slot: true }),
  smokeCase('CardDescription', CardDescription, {}, { slot: true }),
  smokeCase('CardBody', CardBody, {}, { slot: true }),
  smokeCase('CardFooter', CardFooter, {}, { slot: true }),
  smokeCase('AvatarGroup', AvatarGroup, {}),
  smokeCase('Tooltip', Tooltip, {}, { slot: true }),
  smokeCase('EmptyState', EmptyState, { title: 'Nothing here' }),
  smokeCase('Stat', Stat, { label: 'Revenue', value: '1.2k' }),
  smokeCase('Snippet', Snippet, { text: 'pnpm add @wow-two-beta/ui-vue' }),
  smokeCase('NotificationDot', NotificationDot, {}),
  smokeCase('CountBadge', CountBadge, { value: 3 }),
  smokeCase('Status', Status, {}, { slot: true }),
  smokeCase('KeyboardShortcut', KeyboardShortcut, { keys: ['Meta', 'K'] }),
  smokeCase('DescriptionList', DescriptionList, { items: [{ label: 'Plan', value: 'Pro' }] }),
  smokeCase('InfoRow', InfoRow, {}),
  smokeCase('MetricChip', MetricChip, { label: 'CPU', value: '42%' }),
  smokeCase('Eyebrow', Eyebrow, {}, { slot: true }),
  smokeCase('MetaInline', MetaInline, {}, { slot: true }),
  smokeCase('BadgeOverlay', BadgeOverlay, {}, { slot: true }),
  smokeCase('SectionHeader', SectionHeader, {}),
  smokeCase('Highlight', Highlight, { text: 'hello world', query: 'world' }),
  smokeCase('Collapsible', Collapsible, {}, { slot: true }),
  smokeCase('CollapsibleTrigger', CollapsibleTrigger, {}, { slot: true, wrap: inCollapsible }),
  smokeCase('CollapsibleContent', CollapsibleContent, {}, { slot: true, wrap: inCollapsible }),
  smokeCase('Accordion', Accordion, {}, { slot: true }),
  smokeCase('AccordionItem', AccordionItem, { value: 'item-1' }, { slot: true, wrap: inAccordion }),
  smokeCase('AccordionTrigger', AccordionTrigger, {}, { slot: true, wrap: inAccordionItem }),
  smokeCase('AccordionContent', AccordionContent, {}, { slot: true, wrap: inAccordionItem }),
  smokeCase('Tabs', Tabs, {}, { slot: true }),
  smokeCase('TabsList', TabsList, {}, { slot: true, wrap: inTabs }),
  smokeCase('TabsTab', TabsTab, { value: 'tab-1' }, { slot: true, wrap: inTabsList }),
  smokeCase('TabsPanel', TabsPanel, { value: 'tab-1' }, { slot: true, wrap: inTabs }),
  smokeCase('List', List, {}, { slot: true }),
  smokeCase('ListItem', ListItem, {}, { slot: true }),
  smokeCase('Timeline', Timeline, {}),
  smokeCase('TimelineItem', TimelineItem, {}, { slot: true }),
  smokeCase('TimelineTitle', TimelineTitle, {}, { slot: true }),
  smokeCase('TimelineDescription', TimelineDescription, {}, { slot: true }),
  smokeCase('Tree', Tree, {}, { slot: true }),
  smokeCase(
    'TreeGroup',
    TreeGroup,
    { value: 'group-1', label: 'Group' },
    {
      slot: true,
      wrap: inExpandedTree,
    },
  ),
  smokeCase('TreeItem', TreeItem, { value: 'item-1' }, { slot: true, wrap: inTree }),
  smokeCase('Table', Table, {}, { slot: true }),
  smokeCase('TableHead', TableHead, {}, { slot: true }),
  smokeCase('TableBody', TableBody, {}, { slot: true }),
  smokeCase('TableFooter', TableFooter, {}, { slot: true }),
  smokeCase('TableRow', TableRow, {}, { slot: true }),
  smokeCase('TableHeaderCell', TableHeaderCell, {}, { slot: true }),
  smokeCase('TableCell', TableCell, {}, { slot: true }),
  smokeCase('TableCaption', TableCaption, {}, { slot: true }),
  smokeCase('DataTable', DataTable, { columns: [{ key: 'name', header: 'Name' }], data: [{ name: 'Ada' }] }),
  smokeCase('Carousel', Carousel, {}, { slot: true }),
  smokeCase('CarouselViewport', CarouselViewport, {}, { slot: true, wrap: inCarousel }),
  smokeCase('CarouselSlides', CarouselSlides, {}, { wrap: inCarouselViewport }),
  smokeCase('CarouselSlide', CarouselSlide, {}, { slot: true, wrap: inCarouselViewport }),
  smokeCase('CarouselPrev', CarouselPrev, {}, { slot: true, wrap: inCarousel }),
  smokeCase('CarouselNext', CarouselNext, {}, { slot: true, wrap: inCarousel }),
  smokeCase('CarouselDots', CarouselDots, {}, { wrap: inCarousel }),
  smokeCase('CarouselDot', CarouselDot, { slideIndex: 0 }, { wrap: inCarousel }),
  smokeCase('SwipeActions', SwipeActions, {}, { slot: true }),
  smokeCase('DiffViewer', DiffViewer, { left: 'one', right: 'two' }),
  smokeCase('Sparkline', Sparkline, { data: [1, 4, 2, 8] }),
  smokeCase('RadiusGlyph', RadiusGlyph, { extent: 0.5 }),
  smokeCase('FrameGlyph', FrameGlyph, { frameRx: 0.25, pupilRoundness: 0.5 }),
  smokeCase('DotsGlyph', DotsGlyph, {}),
  smokeCase('VerticalBarsGlyph', VerticalBarsGlyph, {}),
  smokeCase('HorizontalBarsGlyph', HorizontalBarsGlyph, {}),
  smokeCase('CellsGlyph', CellsGlyph, { cornerRx: 0.3 }),
  smokeCase('HeatmapCalendar', HeatmapCalendar, { values: new Map<Temporal.PlainDate, number>() }),
  smokeCase('DataGrid', DataGrid, {
    columns: [{ key: 'name', header: 'Name', accessor: (row) => (row as GridRow).name }],
    rows: gridRows,
    rowKey: (row) => (row as GridRow).id,
  }),
  smokeCase('NodeEditor', NodeEditor, { nodes: [{ id: 'n1', x: 0, y: 0 }] }),
  smokeCase('AudioWaveform', AudioWaveform, { peaks: [0.2, 0.8, 0.4] }),
  smokeCase('AudioPlayer', AudioPlayer, { src: 'https://example.test/audio.mp3' }),
  smokeCase('VideoPlayer', VideoPlayer, { src: 'https://example.test/video.mp4' }),
  smokeCase('PDFViewer', PDFViewer, { src: 'https://example.test/doc.pdf' }),
  smokeCase('ScheduleView', ScheduleView, { resources: [{ id: 'r1', label: 'Room 1' }], bookings: [] }),
  smokeCase('Gantt', Gantt, { tasks: [ganttTask] }),
  smokeCase('EventCalendar', EventCalendar, { events: [] }),
  smokeCase('GradientText', GradientText, {}, { slot: true }),
  smokeCase('CountUp', CountUp, { to: 100 }),
  smokeCase('AnimatedNumber', AnimatedNumber, { value: 42 }),
  smokeCase('ScrollReveal', ScrollReveal, {}, { slot: true }),
  smokeCase('Tilt', Tilt, {}, { slot: true }),
  smokeCase('Marquee', Marquee, {}, { slot: true }),
  smokeCase('Typewriter', Typewriter, { text: 'hello' }),
  smokeCase('Confetti', Confetti, {}),
  smokeCase('AnnotationMarker', AnnotationMarker, {}, { slot: true }),
  smokeCase('ReactionBar', ReactionBar, { reactions: [{ key: 'up', emoji: '\u{1F44D}', count: 2 }] }),
  smokeCase('ChatBubble', ChatBubble, {}, { slot: true }),
  smokeCase('MessageList', MessageList, {}, { slot: true }),
  smokeCase('DaySeparator', DaySeparator, { label: 'Today' }),
  smokeCase('ThreadView', ThreadView, {}, { slot: true }),
  smokeCase('CommentThread', CommentThread, {}, { slot: true }),
  smokeCase('Comment', Comment, { author: 'Ada' }, { slot: true }),
  smokeCase('ActivityFeed', ActivityFeed, {}, { slot: true }),
  smokeCase('ActivityItem', ActivityItem, {}, { slot: true }),
  smokeCase('FeatureCard', FeatureCard, { title: 'Fast' }, { slot: true }),
  smokeCase('StepCard', StepCard, { step: 1, title: 'Install' }, { slot: true }),
  smokeCase('PricingCard', PricingCard, { name: 'Pro', price: '$9', features: ['Unlimited seats'] }, { slot: true }),
  smokeCase('Sortable', Sortable, {}, { slot: true }),
  smokeCase('SortableItem', SortableItem, { index: 0 }, { slot: true, wrap: inSortable }),
  smokeCase('SortableHandle', SortableHandle, {}, { slot: true, wrap: inSortableItem }),
];
