import { defineConfig } from 'tsup';

// Component group -> physical layer folder under `src/`. Public subpaths are now
// layer-prefixed (`@wow-two-beta/ui/<layer>/<group>`) and `dist/` mirrors the
// layers 1:1 (`dist/<layer>/<group>/index.*`). Keep in sync with `package.json`
// exports and `apps/lib-source-alias.mjs`.
const subpathLayer: Record<string, 'foundation' | 'domain' | 'presentation'> = {
  utils: 'foundation',
  hooks: 'foundation',
  icons: 'foundation',
  primitives: 'foundation',
  themes: 'foundation',
  http: 'foundation',
  storage: 'foundation',
  resilience: 'foundation',
  identifiers: 'foundation',
  i18n: 'foundation',
  config: 'foundation',
  shortcuts: 'foundation',
  format: 'foundation',
  files: 'foundation',
  commands: 'foundation',
  errors: 'foundation',
  share: 'foundation',
  color: 'domain',
  emoji: 'domain',
  actions: 'presentation',
  display: 'presentation',
  feedback: 'presentation',
  forms: 'presentation',
  layout: 'presentation',
  nav: 'presentation',
  overlays: 'presentation',
};

export default defineConfig({
  entry: {
    index: 'src/index.ts',
    // `router` is a standalone top-level subpath (`@wow-two-beta/ui/router`), not layer-prefixed like
    // the component groups below — this keeps its react-router-dom peer dep out of every other entry.
    'router/index': 'src/router/index.ts',
    // `query` mirrors `router` — a standalone top-level subpath (`@wow-two-beta/ui/query`) whose
    // optional `@tanstack/react-query` peer stays out of every other entry. `query/testing` is a
    // second entry for the test-only helpers (`@wow-two-beta/ui/query/testing`).
    'query/index': 'src/query/index.ts',
    'query/testing': 'src/query/testing.ts',
    // `auth` mirrors `router`/`query` — a standalone top-level subpath (`@wow-two-beta/ui/auth`).
    // It carries no peer of its own (plain React + foundation/http types); kept standalone so the
    // headless session client is importable without any presentation entry.
    'auth/index': 'src/auth/index.ts',
    // `feedback` mirrors `auth` — standalone top-level subpath (`@wow-two-beta/ui/feedback`), no
    // peer of its own; the headless notice bus stays importable without any presentation entry
    // (the `<FeedbackToasts/>` adapter ships in `presentation/feedback`).
    'feedback/index': 'src/feedback/index.ts',
    // `analytics` + `flags` mirror `feedback` — standalone top-level subpaths, no peer of their own. The
    // headless event bus / flag evaluator stay importable without pulling any presentation entry.
    'analytics/index': 'src/analytics/index.ts',
    'flags/index': 'src/flags/index.ts',
    // `forms-engine` — the engine-free forms facade contract (types + glue + server-error
    // pipeline, zero peer). Each engine adapter is its own sibling entry so an adapter's
    // peer never rides along: `forms-engine/house` is the zero-dependency micro-engine;
    // `forms-engine/tanstack` is the default adapter (optional @tanstack/react-form peer
    // → external below) — importing `/forms-engine` or `/house` must never pull it.
    'forms-engine/index': 'src/forms-engine/index.ts',
    'forms-engine/house/index': 'src/forms-engine/house/index.ts',
    'forms-engine/tanstack/index': 'src/forms-engine/tanstack/index.ts',
    // `foundation/storage/zustand` — the zustand-persist adapter. A nested subpath (below the layer-prefixed
    // `foundation/storage`), so it needs an explicit entry rather than the `subpathLayer` one-level generation.
    // No zustand peer: it only mirrors zustand's `PersistStorage` shape structurally (see ZustandPersist.ts).
    'foundation/storage/zustand/index': 'src/foundation/storage/zustand/index.ts',
    // Entry KEY = dist path (`dist/<layer>/<group>/index.js`) — mirrors the
    // layered source folder so the emitted subpath matches the public export.
    ...Object.fromEntries(
      Object.entries(subpathLayer).map(([group, layer]) => [
        `${layer}/${group}/index`,
        `src/${layer}/${group}/index.ts`,
      ]),
    ),
  },
  format: ['esm'],
  banner: { js: '"use client";' }, // whole lib is client-side — keep chunks importable from RSC
  dts: false, // generated by `tsc --emitDeclarationOnly` to avoid rollup-plugin-dts ENFILE issues on macOS
  clean: true,
  sourcemap: true,
  treeshake: true,
  external: [
    'react',
    'react-dom',
    'react-router-dom',
    // Query subpath peers — kept external so `@wow-two-beta/ui/query` carries no bundled RQ and the
    // root/other entries stay RQ-free. `@testing-library/react` (a devDep) is external only so the
    // `query/testing` entry references it rather than inlining it.
    '@tanstack/react-query',
    '@tanstack/react-query-persist-client',
    '@tanstack/query-sync-storage-persister',
    '@tanstack/react-query-devtools',
    // Forms-engine tanstack adapter peer — external so `forms-engine/tanstack` references
    // it and the contract entry + house adapter chunks stay @tanstack/react-form-free.
    '@tanstack/react-form',
    '@testing-library/react',
  ],
});
