export {
  Table,
  TableHead,
  TableBody,
  TableFooter,
  TableRow,
  TableHeaderCell,
  TableCell,
  TableCaption,
  TableDensity,
  TableRadius,
  TableHeadVariant,
  type TableProps,
  type TableHeadProps,
  type TableHeaderCellProps,
  type TableCellProps,
} from './Table';
